name: Bug Report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: "For security issues, do NOT file a public bug. Use private security reporting."
  - type: textarea
    id: summary
    attributes:
      label: Summary
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
