name: Security Report
description: Security reports should be private
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        Do NOT disclose vulnerabilities publicly.
        Use GitHub Security Advisories private reporting for this repository.
  - type: textarea
    id: contact
    attributes:
      label: Contact Information
  - type: textarea
    id: details
    attributes:
      label: Vulnerability Details (high-level)
